-- ============================================================================
-- CAA doc-to-KB collection schema — SingleStore-compatible DDL
-- ============================================================================
-- Step 0 gate note:
-- Native SingleStore vector column compatibility is still awaiting MUFG-side
-- evidence. `CAA_KB_EMBEDDING.EMBEDDING_VECTOR_JSON` is therefore an interim
-- JSON vector payload, and must be revisited before Step 5+ ingestion is made
-- production-green.

CREATE TABLE CAA_KB_COLLECTION (
    COLLECTION_IDENTIFIER           VARCHAR(64)     NOT NULL,
    USER_IDENTIFIER                 VARCHAR(64)     NOT NULL,
    COLLECTION_NAME                 VARCHAR(256)    NOT NULL,
    INGESTION_STATUS                VARCHAR(32)     NOT NULL DEFAULT 'pending',
    EFFECTIVE_FROM_TIMESTAMP        DATETIME        NOT NULL,
    ACTIVE_INDICATOR                TINYINT         NOT NULL DEFAULT 1,
    As_of_Timestamp                 DATETIME        NOT NULL,
    PRIMARY KEY (COLLECTION_IDENTIFIER),
    UNIQUE KEY UQ_CAA_KB_COLLECTION_USER_NAME_ACTIVE
        (USER_IDENTIFIER, COLLECTION_NAME, ACTIVE_INDICATOR),
    CHECK (INGESTION_STATUS IN ('pending', 'ready', 'failed')),
    INDEX IDX_CAA_KB_COLLECTION_USER_ACTIVE (USER_IDENTIFIER, ACTIVE_INDICATOR)
);

CREATE TABLE CAA_KB_MEMBER (
    MEMBER_IDENTIFIER               VARCHAR(64)     NOT NULL,
    COLLECTION_IDENTIFIER           VARCHAR(64)     NOT NULL,
    ANALYSIS_IDENTIFIER             VARCHAR(64)     NOT NULL,
    SOURCE_FILENAME                 VARCHAR(512)    NULL,
    INGESTION_STATUS                VARCHAR(32)     NOT NULL DEFAULT 'pending',
    EFFECTIVE_FROM_TIMESTAMP        DATETIME        NOT NULL,
    ACTIVE_INDICATOR                TINYINT         NOT NULL DEFAULT 1,
    As_of_Timestamp                 DATETIME        NOT NULL,
    PRIMARY KEY (MEMBER_IDENTIFIER),
    UNIQUE KEY UQ_CAA_KB_MEMBER_ANALYSIS (COLLECTION_IDENTIFIER, ANALYSIS_IDENTIFIER),
    CHECK (INGESTION_STATUS IN ('pending', 'ready', 'failed')),
    INDEX IDX_CAA_KB_MEMBER_COLLECTION_ACTIVE (COLLECTION_IDENTIFIER, ACTIVE_INDICATOR),
    CONSTRAINT FK_CAA_KB_MEMBER_COLLECTION
        FOREIGN KEY (COLLECTION_IDENTIFIER)
        REFERENCES CAA_KB_COLLECTION (COLLECTION_IDENTIFIER),
    CONSTRAINT FK_CAA_KB_MEMBER_ANALYSIS
        FOREIGN KEY (ANALYSIS_IDENTIFIER)
        REFERENCES CAA_ANALYSIS (ANALYSIS_IDENTIFIER)
);

CREATE TABLE CAA_KB_EMBEDDING (
    EMBEDDING_IDENTIFIER            VARCHAR(96)     NOT NULL,
    MEMBER_IDENTIFIER               VARCHAR(64)     NOT NULL,
    ANALYSIS_IDENTIFIER             VARCHAR(64)     NOT NULL,
    CHUNK_IDENTIFIER                VARCHAR(96)     NOT NULL,
    NODE_IDENTIFIER                 VARCHAR(128)    NULL,
    EMBEDDING_GRANULARITY           VARCHAR(16)     NOT NULL DEFAULT 'doc',
    EMBEDDING_MODEL_IDENTIFIER      VARCHAR(128)    NOT NULL,
    EMBEDDING_VECTOR_JSON           JSON            NOT NULL,
    CHUNK_TEXT_PREVIEW              VARCHAR(500)    NULL,
    EFFECTIVE_FROM_TIMESTAMP        DATETIME        NOT NULL,
    ACTIVE_INDICATOR                TINYINT         NOT NULL DEFAULT 1,
    As_of_Timestamp                 DATETIME        NOT NULL,
    PRIMARY KEY (EMBEDDING_IDENTIFIER),
    CHECK (EMBEDDING_GRANULARITY IN ('doc', 'node')),
    INDEX IDX_CAA_KB_EMBEDDING_MEMBER_ACTIVE (MEMBER_IDENTIFIER, ACTIVE_INDICATOR),
    INDEX IDX_CAA_KB_EMBEDDING_ANALYSIS (ANALYSIS_IDENTIFIER),
    CONSTRAINT FK_CAA_KB_EMBEDDING_MEMBER
        FOREIGN KEY (MEMBER_IDENTIFIER)
        REFERENCES CAA_KB_MEMBER (MEMBER_IDENTIFIER),
    CONSTRAINT FK_CAA_KB_EMBEDDING_ANALYSIS
        FOREIGN KEY (ANALYSIS_IDENTIFIER)
        REFERENCES CAA_ANALYSIS (ANALYSIS_IDENTIFIER)
);
