-- Drop KB tables in dependency order. Intended for dev/test rebuilds only.

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CAA_KB_EMBEDDING;
DROP TABLE IF EXISTS CAA_KB_MEMBER;
DROP TABLE IF EXISTS CAA_KB_COLLECTION;

SET FOREIGN_KEY_CHECKS = 1;
